version: "2.4"
services:
  prometheus:
    image: "prom/prometheus:v2.16.0"
    container_name: "prometheus"
    restart: always
    user: "${DEFAULT_USER}"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "9090:9090"
  kotbot:
    image: heapy/kotbot:${KOTBOT_RELEASE}
    container_name: kotbot
    restart: always
    volumes:
      - ${KOTBOT_DATA}/db/:/kotbot/db/
    environment:
      KOTBOT_OPTS: ${KOTBOT_OPTS}
      KOTBOT_TOKEN: ${KOTBOT_TOKEN}
      KOTBOT_RELEASE: ${KOTBOT_RELEASE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    mem_limit: 256m
    mem_swappiness: 0
