# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "heapy-kotbot"
    metrics_path: "/api/metrics"
    scrape_interval: 30s
    static_configs:
      - targets: ["kotbot:8080"]
